# ----------------------------------------------------------------------------------------------------
# Code Scanning Template
# ----------------------------------------------------------------------------------------------------
# Microsoft Secure DevOps Scan
# To enable this, you must add Azure DevOps Extension to your Azure DevOps Organization
# See https://marketplace.visualstudio.com/items?itemName=ms-securitydevops.microsoft-security-devops-azdevops
# ----------------------------------------------------------------------------------------------------
stages:
  - stage: ScanStage
    displayName: Scan Code
    jobs:
    - deployment: CodeScanDeployment
      displayName: Initialize Code Scans 
      environment: 'DEV'
    - job: DevSecOpsScanJob
      displayName: DevSecOps Scan Job 
      steps:
      - task: UseDotNet@2
        displayName: 'Use dotnet 8.0'
        inputs:
          version: 8.0.x
      - task: MicrosoftSecurityDevOps@1
        displayName: 'Run Microsoft Security DevOps'
        continueOnError: true
